pool:
  name: Hosted VS2017
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.4'
  inputs:
    versionSpec: 4.9.4

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: Template.nuspec

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
